package za.co.ashleagardens.coc;

import java.awt.FlowLayout;
import za.co.ashleagardens.coc.panels.SongVerseChooserPanel;
import java.awt.event.WindowEvent;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JWindow;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import za.co.ashleagardens.coc.panels.AboutPanel;
import za.co.ashleagardens.coc.panels.PropertySheetPanel;

/**
 *
 * @author Deon
 */
public class CocSongReaderApp extends javax.swing.JFrame {

    private static final Logger LOGGER = LoggerFactory.getLogger(CocSongReaderApp.class);

    private SongVerseChooserPanel songVerseChooserPanel;

    //TODO: add logging
//     private static final Logger LOGGER;
    /**
     * Creates new form CocSongReader
     */
    public CocSongReaderApp() {
        initComponents();

        this.pack();
        addSongVerseChooserPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cocSongReaderMenu = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openFileMenuItem = new javax.swing.JMenuItem();
        closeAppMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        preferencesMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();
        tutorialMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ashlea Gardens Song Reader");
        setMaximumSize(new java.awt.Dimension(400, 350));
        setMinimumSize(new java.awt.Dimension(400, 350));
        setName("cocSongReaderAppFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(400, 350));
        setResizable(false);

        fileMenu.setText("File");

        openFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openFileMenuItem.setText("Open File");
        openFileMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                openFileMenuItemMousePressed(evt);
            }
        });
        fileMenu.add(openFileMenuItem);

        closeAppMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
        closeAppMenuItem.setText("Close");
        closeAppMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeAppMenuItemMousePressed(evt);
            }
        });
        fileMenu.add(closeAppMenuItem);

        cocSongReaderMenu.add(fileMenu);

        editMenu.setText("Edit");

        preferencesMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        preferencesMenuItem.setText("Preferences");
        preferencesMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                preferencesMenuItemMousePressed(evt);
            }
        });
        editMenu.add(preferencesMenuItem);

        cocSongReaderMenu.add(editMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aboutMenuItem.setText("About");
        aboutMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aboutMenuItemMousePressed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        tutorialMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        tutorialMenuItem.setText("Tutorial");
        helpMenu.add(tutorialMenuItem);

        cocSongReaderMenu.add(helpMenu);

        setJMenuBar(cocSongReaderMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMenuItemMousePressed
        JDialog.setDefaultLookAndFeelDecorated(true);
        JDialog dialog = new JDialog(this, "About", true);
        dialog.setLayout(new FlowLayout());
        dialog.add(new AboutPanel());
        dialog.setSize(this.getContentPane().getSize());
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_aboutMenuItemMousePressed

    private void openFileMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openFileMenuItemMousePressed
        addSongVerseChooserPanel();
    }//GEN-LAST:event_openFileMenuItemMousePressed

    private void closeAppMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeAppMenuItemMousePressed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_closeAppMenuItemMousePressed

    private void preferencesMenuItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preferencesMenuItemMousePressed
        JDialog.setDefaultLookAndFeelDecorated(true);
        JDialog dialog = new JDialog(this, "Application properties", true);
        dialog.setLayout(new FlowLayout());
        dialog.add(new PropertySheetPanel(dialog));
        dialog.setSize(this.getContentPane().getSize());
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_preferencesMenuItemMousePressed

    
    private void addSongVerseChooserPanel() {
        songVerseChooserPanel = new SongVerseChooserPanel(this.getContentPane().getSize());
        songVerseChooserPanel.setVisible(true);
        this.add(songVerseChooserPanel);
        this.validate();
        this.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    //Windows LAF
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
                    //TODO: add logging
                }
                CocSongReaderApp app = new CocSongReaderApp();
                app.setVisible(true);
                app.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem closeAppMenuItem;
    private javax.swing.JMenuBar cocSongReaderMenu;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem openFileMenuItem;
    private javax.swing.JMenuItem preferencesMenuItem;
    private javax.swing.JMenuItem tutorialMenuItem;
    // End of variables declaration//GEN-END:variables
}
