package za.co.ashleagardens.coc.panels;

import za.co.ashleagardens.coc.components.PropertyTable;
import org.apache.commons.configuration.ConfigurationException;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import za.co.ashleagardens.coc.util.PropertyUtil;

/**
 *
 * @author Deon
 */
public class PropertySheetPanel extends javax.swing.JPanel {

    private static final PropertyUtil propertyUtil = PropertyUtil.INSTANCE;
    private static final Logger LOGGER = LoggerFactory.getLogger(PropertySheetPanel.class);

    /**
     * Creates new form PropertySheetPanel
     */
    public PropertySheetPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        propertyTableScrollPane = new javax.swing.JScrollPane();
        try {
            propertyTable = new PropertyTable(propertyUtil.getApplicationProperties());

        } catch (ConfigurationException ex) {
            LOGGER.error(ex.getMessage());
        }
        propertyTable.getTableHeader().setReorderingAllowed(false);
        propertyTableScrollPane.setViewportView(propertyTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(propertyTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(propertyTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable propertyTable;
    private javax.swing.JScrollPane propertyTableScrollPane;
    // End of variables declaration//GEN-END:variables

}
